### PR TITLE
Updates javascript library to beta 8

### PR DESCRIPTION
**Pull request by scuml**
Update the javascript library.

### CODE REVIEW

**Comment by C4ptainCrunch** [comment]
Hi @scuml !

It seems like @hotwire-django/maintainers (which I am part of) are quite busy at the moment (or, like me, got discouraged by the events at Basecamp a few months ago and are looking more at htmx). However, this should not stop new contributions to the project.

We believe in do-it-ocracy and as you seem quite motivated and did a few PR, would you like to get write access to the repositories ? Just tell me and i'll add you to the team here on GitHub and on Slack :)

**Comment by scuml** [comment]
Yes, please.

**Comment by C4ptainCrunch** [comment]
Great! You got an invite to join the maintainers team 🚀 
Welcome :)

I can also invite you on #organization on Slack if you join the workspace and ping me (@0xC4) but i warn you, there is close to 0 traffic over there ^^

**Comment by scuml** [comment]
Thanks.  The slack channel is currently locked to `pragmaticminds.de` email domains and I cannot join.

**Comment by C4ptainCrunch** [comment]
Could you try this link ? https://join.slack.com/t/hotwire-django/shared_invite/zt-tgq2lydh-zrPW_H0a4ZJTL469FqSPPw

**Comment by scuml** [comment]
Rolled into #37

**Pull request closed without merging**
