### PR TITLE
Bugfix/20 websocket not connecting

### PR DESCRIPTION
**Pull request by JulianFeinauer**
Force a reconnect when the Tag is initialized.

(also added html / js files to setup.cfg)

### CODE REVIEW

**Comment by C4ptainCrunch** [comment]
From what [i understand](https://github.com/pladaria/reconnecting-websocket/blob/master/reconnecting-websocket.ts#L244-L245), `reconnect()` closes the socket and re-opens a new one. I think this not something desirable to do on every turbo drive visit, right ?

**Comment by JulianFeinauer** [comment]
> From what [i understand](https://github.com/pladaria/reconnecting-websocket/blob/master/reconnecting-websocket.ts#L244-L245), `reconnect()` closes the socket and re-opens a new one. I think this not something desirable to do on every turbo drive visit, right ?

Indeed, you are right. This should probably be conditional on if it's already connected or something. That's just what made it work for me but I like to hear comments from the experts like @davish or @danjac!

**Comment by blopker** [comment]
Right, ideally we'd check if it's connected or now. However, we are using that reconnecting websocket library, why isn't that taking care of it? Something's fishy here.

**Comment by JulianFeinauer** [comment]
> Right, ideally we'd check if it's connected or now. However, we are using that reconnecting websocket library, why isn't that taking care of it? Something's fishy here.

I guess that's some reconnect timeout limit hitting here OR it's already connected before the handlers are registered. So in this case they should go on and start without waiting for open, right?

**Comment by blopker** [comment]
I could help take a look at the issue if you have a minimal reproduction I could look at?

**Comment by JulianFeinauer** [comment]
I finally found a "elegant" solution (IMHO) and also discussed with @blopker.
From my perspectigve this is fine now but some Tests wouldn't hurt, I guess.

But I have honestly no idea how to do that. Anyone else? @jonathan_s?

**Review by davish — APPROVED** [review]
This looks good to me! It keeps in mind how the reconnecting websocket library will automatically restart connections. It's good that we re-send the subs on open. Merge when ready 😄 

In terms of testing, I'm thinking more and more that for the websocket things, integration tests through cypress would be the best way to go, but that can be a separate issue :)

**Comment by JulianFeinauer** [comment]
Thanks and Agree!

**Pull request merged**
