### PR TITLE
Vendor JS Libs

### PR DESCRIPTION
**Pull request by blopker**
This PR vendors the JS libraries. This is useful so users of this package don't have to rely on third party CDNs which is against many companies' security policies and adds another failure point to sites. If people want to use other versions of the vendored libs or want to create their own JS bundle, it should be easy enough to just not include the `head.html` template and use their own solution.

List of changes:

- Changed chat app setup instructions to use Python 3's built in `venv` module so we don't rely on the `virtualvenv` package being installed globally.
- Added some seed data to the chat app so people can get set up easier.
- Removed `channels` from `install_requires` so people using WSGI don't need to have it installed. We'll want to mention something about installing it in the Streams install instructions. 
- Moved the previously inline JS into its own JS file, then wrapped it in IIFE so variables don't leak. We can minify this at some point, but it's so small now it didn't seem worth it.
- Changed turbo.js to load the es2017 version as our custom JS wont work on es5 anyway.
- Changed reconnecting-websocket to the IIFE version minified which is smaller and avoids an exception with the CJS version.
- Used the `static` tag with `data-turbo-track="reload"` so the JS files get fingerprinted and Turbo reloads itself when those resources change in production. 
- Added `defer` to script tags so they don't block rendering the rest of the page.
- Dynamically create the websocket URL to work in other environments besides `localhost`, also now supports secure connections.

### CODE REVIEW

**Review by davish — APPROVED** [review]
Looks great! The data fixture is a great addition to the demo app, too :D

**Comment by blopker** [comment]
Thanks for the review @davish! I'm part of this org now, but still can't merge this PR. Can you add me to this repo? If you make me an admin I can help add people too as needed.

**Comment by davish** [comment]
Hmm... I also don't have admin access but I can merge, since I think I asked @C4ptainCrunch to make me a maintainer. @C4ptainCrunch could you add @blopker to the maintainer list so he can merge the PR? I can also merge this one in myself

**Comment by blopker** [comment]
Ah, too bad! If you could, please go ahead and merge this so we can move forward. It would be good to get admin access for one or both of us for this repo so we can set up things like GitHub actions.

**Comment by C4ptainCrunch** [comment]
You are now both in the @hotwire-django/maintainers team that should grant you almost every access on turbo-django, stimulus-django and hotwire-django :)

**Pull request merged**
